//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPrices
    {
        public int PriceID { get; set; }
        public Nullable<int> CarID { get; set; }
        public decimal DailyPrice { get; set; }
    
        public virtual Cars Cars { get; set; }
    }
}
