//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Returns
    {
        public int ReturnID { get; set; }
        public Nullable<int> RentalID { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public Nullable<int> ConditionID { get; set; }
    
        public virtual Rentals Rentals { get; set; }
        public virtual ReturnCondition ReturnCondition { get; set; }
    }
}
